import type { ProductCardProps } from "../../molecules/ProductCard/types";
import imgArCondicionado from "../../../assets/imgs/img_ar_condicionado.png";

export const CATALOG_PRODUCTS_MOCK: ProductCardProps[] = [
    {
        id: "1",
        image: imgArCondicionado,
        title: "Ar Condicionado Split 9000 BTUs",
        originalPrice: 1899.0,
        price: 1599.0,
        discount: 16,
        tag: "oferta",
    },
    {
        id: "2",
        image: imgArCondicionado,
        title: "Ar Condicionado Split 12000 BTUs Inverter",
        originalPrice: 2699.0,
        price: 2299.0,
        discount: 15,
        tag: "prime",
    },
    {
        id: "3",
        image: imgArCondicionado,
        title: "Ar Condicionado Split 18000 BTUs",
        originalPrice: 3299.0,
        price: 2799.0,
        discount: 15,
        tag: "oferta",
    },
    {
        id: "4",
        image: imgArCondicionado,
        title: "Ar Condicionado Split 24000 BTUs Inverter",
        originalPrice: 4199.0,
        price: 3699.0,
        discount: 12,
        tag: "prime",
    },
    {
        id: "5",
        image: imgArCondicionado,
        title: "Ar Condicionado Split 30000 BTUs",
        originalPrice: 5299.0,
        price: 4599.0,
        discount: 13,
        tag: "oferta",
    },
    {
        id: "6",
        image: imgArCondicionado,
        title: "Ar Condicionado Cassete 36000 BTUs",
        originalPrice: 6499.0,
        price: 5799.0,
        discount: 11,
        tag: "prime",
    },
    {
        id: "7",
        image: imgArCondicionado,
        title: "Ar Condicionado Piso Teto 48000 BTUs",
        originalPrice: 7899.0,
        price: 6999.0,
        discount: 11,
        tag: "oferta",
    },
    {
        id: "8",
        image: imgArCondicionado,
        title: "Ar Condicionado VRF 60000 BTUs",
        originalPrice: 12999.0,
        price: 10999.0,
        discount: 15,
        tag: "prime",
    },
];
