import type { Testimonial } from "./types";

export const TESTIMONIALS_MOCK: Testimonial[] = [
    {
        id: "1",
        name: "João Silva",
        avatar: "https://i.pravatar.cc/150?img=12",
        servicesCount: 5,
        rating: 5,
        description: "Já contratei a Vitte Climatização várias vezes para N serviços e manutenção de ar-condicionado, e posso afirmar com toda certeza: é um profissional de confiança, responsável e muito competente. Todas as vezes que precisei, ele atendeu com pontualidade, resolveu tudo com excelência técnica e ainda teve o cuidado de explicar cada detalhe do serviço realizado.",
        likes: 42,
        isLiked: false,
    },
    {
        id: "2",
        name: "Maria Santos",
        avatar: "https://i.pravatar.cc/150?img=5",
        servicesCount: 3,
        rating: 5,
        description: "Excelente serviço! A equipe foi muito profissional, pontual e o trabalho ficou perfeito. Recomendo muito!",
        likes: 28,
        isLiked: false,
    },
    {
        id: "3",
        name: "Carlos Oliveira",
        avatar: "https://i.pravatar.cc/150?img=33",
        servicesCount: 7,
        rating: 4,
        description: "Muito satisfeito com o atendimento. A instalação do ar-condicionado foi rápida e bem feita. O técnico foi atencioso e tirou todas as minhas dúvidas sobre o funcionamento do equipamento.",
        likes: 35,
        isLiked: false,
    },
    {
        id: "4",
        name: "Ana Paula",
        avatar: "https://i.pravatar.cc/150?img=9",
        servicesCount: 2,
        rating: 5,
        description: "Serviço impecável! Precisava de uma manutenção urgente e eles conseguiram atender no mesmo dia. O ar voltou a funcionar perfeitamente.",
        likes: 19,
        isLiked: false,
    },
    {
        id: "5",
        name: "Roberto Mendes",
        avatar: "https://i.pravatar.cc/150?img=15",
        servicesCount: 4,
        rating: 5,
        description: "Já contratei a Vitte Climatização várias vezes para N serviços e manutenção de ar-condicionado, e posso afirmar com toda certeza: é um profissional de confiança, responsável e muito competente. Todas as vezes que precisei, ele atendeu com pontualidade, resolveu tudo com excelência técnica.",
        likes: 51,
        isLiked: false,
    },
    {
        id: "6",
        name: "Fernanda Lima",
        avatar: "https://i.pravatar.cc/150?img=10",
        servicesCount: 1,
        rating: 4,
        description: "Ótimo custo-benefício e atendimento de qualidade. A instalação foi feita com cuidado e o local ficou limpo após o serviço.",
        likes: 23,
        isLiked: false,
    },
];
